server:
  port: 8080

spring:
  application:
    name: huta-booking

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/huta_booking
    username: postgres
    password: sa2008
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE